---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion
spec:
  selector:
    matchLabels:
      app: motion
  replicas: 1
  template: 
    metadata:
      labels:
        app: motion
    spec:
      imagePullSecrets:
      - name: regcred
      terminationGracePeriodSeconds: 120
      containers:
      - name: motion
        image: docker.io/appsoa/docker-alpine-motion:3.4
        imagePullPolicy: Always
        command: ["/entrypoint.sh"]
        args: ["run.sh", "/conf/tested.30fps.1pic.conf", "stable.conf"]
        ports:
        - containerPort: 8081
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: ["SYS_ADMIN"]
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty", "streaming-platform-vod-01", "/storage-bucket"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "wait $(pidof motion) && fusermount -u /storage-bucket & pkill motion"]
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: gcloud-key
          mountPath: /var/secrets/google
        env:
        - name: MOTION_CONF_TEMPLATE
          value: /conf/tested.30fps.1pic.conf
        - name: CAMERA_ID
          value: 79da5c31-5b78-44f7-9c0d-2e858cd598f3
        - name: MOTION_URL
          value: "rtsp://admin:Speco123001!@decaro.streamnvr.com:11200"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      volumes:
        - name: gcloud-key
          configMap:
            name: gcloud-key
